language: android
jdk: oraclejdk7

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - tools
    - tools
    - android-26
    - build-tools-27.0.3
    - platform-tools
    - extra-android-support
    - extra-google-m2repository

before_script: echo y | ${ANDROID_HOME}tools/bin/sdkmanager --channel=3 "tools" "platform-tools" "platforms;android-27"
script: ./gradlew build

after_failure:
  - cat app/build/reports/tests/testDebugUnitTest/index.html
